language: python
python: 
    - 3.6
install:
    - pip install -r requirements.txt
script:
    - python manage.py test

addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable